### ISSUE TITLE
it would be better to give an example about how to use them 

### ISSUE THREAD

**Issue by 1a1a11a** [nemequ/gnome-cmake#6]
I am learning cmake and this repo is handy, but for beginners, providing an example about how to use the cmake might be better.

**Comment by nemequ** [comment]
Which module(s) do you need?  For Vala IIRC https://github.com/flplv/vala-cmake-example uses them.  I'd be happy to add links to examples, but I don't expect to have time to write any.

GNOME seems to be moving towards [Meson](http://mesonbuild.com/) these days. If you're starting a new project you might want to consider using that instead.

**Comment by 1a1a11a** [comment]
I am using glib, I am trying to incorporate glib into my CMakeLists.txt, simple Googling does not find some easy resource, still diving in the search results to learn. 
The link you posted is very helpful, but still does not solve all of my problems. And thank you for letting me know Meson, it's awesome!

**Comment by 1a1a11a** [comment]
a snippet of my current CMakeLists.txt looks like this, the problem is that program cannot find `glib.h` 



```
find_package(GLib "2.50" REQUIRED)
include_directories(${GLIB_INCLUDE_DIR})
set(LIBS ${LIBS} ${GLIB_LIBRARIES}) 

aux_source_directory(. DIR_SRCS)
add_subdirectory(utils)
add_executable(test ${DIR_SRCS})
target_link_libraries(test utils ${LIBS})
```

**Comment by nemequ** [comment]
Try

```cmake
find_package(GLib "2.50" REQUIRED)
include_directories(${GLib_INCLUDE_DIRS})
set(LIBS ${LIBS} ${GLib_LIBRARY}) 

aux_source_directory(. DIR_SRCS)
add_subdirectory(utils)
add_executable(test ${DIR_SRCS})
target_link_libraries(test utils ${LIBS})
```

Notice the camel case in GLib, DIRS instead of DIR, and LIBRARY instead of LIBRARIES.

You can use something like `message(FATAL_ERROR $VARNAME)` to inspect the contents of variables to make sure they make sense.

**Comment by nemequ** [comment]
Unless you have a compelling reason for using CMake (*e.g.*, your company has standardized on it), Meson is probably a better choice.  It's a big improvement over CMake; much more so than CMake is an improvement over autotools…  The biggest disadvantage I'm aware of is that it requires a newish Python (IIRC it was 3.3 last time I checked, which was released in 2012), so very old distros may not work out of the box.

**Comment by 1a1a11a** [comment]
finally, make it work, the upper and lowercase drives me crazy, original glib has lowercase, find_package use GLib, some tutorials use GLIB. using `message` is really helpful, thank you so much! (This is an academic project, so I can use whatever I want) I have read the meson tutorial, it seems I need to enumerate all the files? And this project involves both C and C++ I didn't find support for that in meson too (but I guess I can use g++ for the the sources).

**Comment by nemequ** [comment]
It's generally considered much better to list all the files in your build system anyways; the list isn't hard to maintain, and it's a lot less fragile.  There is even a warning about that in the cmake docs for the glob argument of the [file](https://cmake.org/cmake/help/v3.8/command/file.html) function:

> Note: We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate.

I wouldn't be surprised if meson has something similar, but I also wouldn't be surprised if it doesn't.

Neither Meson nor CMake should have any trouble mixing C and C++, there is no need to try to use a C++ compiler for C.

FWIW, the #mesonbuild IRC channel (on freenode) is very helpful.  #cmake has more people, but everyone mostly just lurks.

**Comment by 1a1a11a** [comment]
Good to know that, then I should list all the source files. 
I will have a try of meson, thank you for all the information, it is really helpful. I guess thank you is not enough for my appreciation. :)
